version: '3'

services:
  postgres:  # Changed from pgdatabase to match Airflow connection
    image: postgres:15
    environment: 
      POSTGRES_USER: airflow  # Changed to match Airflow's expectation
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow  # Changed from ny_airbnb
    ports:
      - "5432:5432"
    healthcheck:  # Added healthcheck
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes: 
      - ./pgadmin:/var/lib/pgadmin:rw
    ports:
      - "8081:80"  # Changed from 8080 to avoid conflict

  airflow-webserver:
    image: apache/airflow:2.7.2
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: 'UTC'
    volumes:
      - ./logs:/opt/airflow/logs # Points to your dags directory
      - ./plugins:/opt/airflow/plugins
      - ./dags:/opt/airflow/dags
      - ../load:/opt/airflow/load 
      - ../dbt_transform:/opt/airflow/dbt_transform

    ports:
      - "8080:8080"  # Airflow keeps 8080
    command: >
      bash -c "
      pip install dbt-core dbt-bigquery apache-airflow-providers-google &&
      airflow db init &&
      airflow users create --username admin --firstname dezoomcamp --lastname ww --role Admin --email ytwyolo66@gmail.com --password dezoomcamp &&
      (airflow scheduler & airflow webserver --port 8080)
      "
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3